openapi: 3.0.0
info:
  title: API Example
paths:
  /order:
    post:
      summary: Submit an order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                name:
                  type: string
                count:
                  type: string
      proxy_mapping:
        proxy_host: http://localhost:8080
        proxy_endpoint: /proxy-order
        proxy_method: post
        field_mappings:
          orderId: id
          name: product
          count: quantity
    get:
      proxy_mapping:
        proxy_host: http://localhost:8080
        proxy_endpoint: /proxy-order
        proxy_method: get
        field_mappings:
          orderId: id
          name: product
          count: quantity
  /payment:
    post:
      summary: Update an order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                status:
                  type: string
      proxy_mapping:
        proxy_host: http://localhost:8080
        proxy_endpoint: /payment-order
        proxy_method: put
        field_mappings:
          id: orderId
          status: orderStatus